### ISSUE TITLE
`server_version` not sent in parameter_status at end of authentication

### ISSUE THREAD

**Issue by acco** [supabase/supavisor#100]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Many clients will error when connecting to Supavisor. For example, consider Postgrex:

```
14:05:01.372 mfa=:gen_statem.error_info/7 pid=<0.1963.0> [error] GenStateMachine #PID<0.1963.0> terminating
** (FunctionClauseError) no function clause matching in String.split/3
    (elixir 1.14.3) lib/string.ex:479: String.split(nil, " ", [parts: 2])
    (postgrex 0.16.5) lib/postgrex/utils.ex:68: Postgrex.Utils.parse_version/1
    (postgrex 0.16.5) lib/postgrex/protocol.ex:1019: Postgrex.Protocol.bootstrap_send/3
    (postgrex 0.16.5) lib/postgrex/protocol.ex:661: Postgrex.Protocol.handshake/2
    (postgrex 0.16.5) lib/postgrex/protocol.ex:166: Postgrex.Protocol.connect_endpoints/6
    (db_connection 2.5.0) lib/db_connection/connection.ex:90: DBConnection.Connection.handle_event/4
    (stdlib 4.3.1) gen_statem.erl:1428: :gen_statem.loop_state_callback/11
    (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

This is because after sending `AuthenticationOk`, the server is expected to send ParameterStatus. Supavisor [does this here](https://github.com/supabase/supavisor/blob/6feb26c55db50f9b2e2ff173a771355036d0ceee/lib/supavisor/client_handler.ex#LL128C47-L128C55).

However, there's a race condition. If the DbHandler hasn't finished _its_ authentication flow, the Manager will not have the parameter_status set -- it will be its default `[]`. This means clients will be sent nothing for ParameterStatus, which seems to cause errors in eg Postgrex.

Once parameter_status is set (the DbHandler has finished authenticating and has set that state in Manager), things work normally.

## To Reproduce

Run `Postgrex.start_link` against a cold Supavisor instance.

## Expected behavior

Postgrex.start_link starts without any errors.

## Implementation

I'm happy to help with implementation, but I struggled a bit with design. I considered having `Manager.get_parameter_status` hang until `parameter_status` was set. But this feels like a workaround. If DbHandler fails to connect (auth is actually bad), ClientHandler will hang inexplicably.

I think we really want the ClientHandler to be intimately connected to the initial connection process to the database. Not only does it care about the ParameterStatus coming from the db. It should also proxy an error to the client if there is a login error (host actually not reachable, password is bad). I wonder if it should run the initial auth process against the db? Or, maybe, if the Manager was just booted (this is a fresh connection pool), it should await some startup process which includes running auth and grabbing ParameterStatus from the db.

**Comment by abc3** [comment]
Thanks for reporting! For our internal needs, we want to allow connections even if the database is not responding. However, it, of course, sucks if the client fails on a cold start, especially when it's `Postgrex`. 

As a potential solution, I suggest adding a wait timeout. During this period, if we receive `parameter_status` from the database, we can forward it to the client, or alternatively, send a "stub" packet with a server version of `0.0`. 
I prepared a small fix #101, WDYT? 

cc @chasers

**Comment by acco** [comment]
@abc3 Just took a look at your PR -- looks like a great solution! This feels right to me. I just ran some tests against your branch and it worked great.

Tangential question: what happens if Supavisor can't establish a connection to the db? i.e. the password both the user used and that's stored in `tenants` turns out to be incorrect?

**Comment by abc3** [comment]
> what happens if Supavisor can't establish a connection to the db? i.e. the password both the user used and that's stored in tenants turns out to be incorrect?

Hmm, yeah, that behavior creates an infinite loop in the `db_handler` until the manager kills the connection tree 🤦‍♂️ 
I'll fix this and make it more robust in a separate PR

**Comment by abc3** [comment]
Could you take a look at #114 fix? It will stop the `DbHandler` retries, and the next client connection attempt will relaunch the pools with the correct credentials
