### ISSUE TITLE
`ClientHandler` and `DbHandler` can deadlock

### ISSUE THREAD

**Issue by acco** [supabase/supavisor#106]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

ClientHandler uses `GenServer.call` to send messages to DbHandler. Likewise, DbHandler uses `GenServer.call` to send database responses back to ClientHandler.

Alas, this can deadlock. 

## To Reproduce

I can reliably reproduce when running a bunch of heavy queries with a lot of data each direction. But basically, the two sockets just need to receive data at roughly the same time for a deadlock to occur. You can increase chances of it happening by introducing a small wait in either `handle_event`.

## Ideas

Perhaps DbHandler can fire-and-forget its messages to ClientHandler (e.g. cast)?

Alternatively, one of them probably needs to spin up a process to send data to the other one (in order to async hear back if it went OK).

**Comment by acco** [comment]
Hmm... I'm actually not so sure this is true:

> Perhaps in theory the two can't deadlock, because the Postgres protocol is pretty strictly turn based?

I can't say for sure, but it seems like due to "Pipelining" (in the [protocol docs](https://www.postgresql.org/docs/15/protocol-flow.html)), you can have a situation where the client is continuing to send messages to the database, while the database responds as it handles those messages.

**Comment by abc3** [comment]
Hmmm, I'll revisit this topic. Thanks for pointing it out to me 👍
