### ISSUE TITLE
Start pools even if user isn't in user table

### ISSUE THREAD

**Issue by chasers** [supabase/supavisor#120]
- [x] Use some "default user pool config" with a `pool_size`
- [x] `pool_type` should be based on port maybe - `5432` = `session` and `6543` = `transaction`
- [x] Flag on tenant record for `require_user` and if `require_user` is `false` we allow user creds to pull from connection string or other method
- [x] `require_user` field default `false`
- [x] Authentication of user to tenant database will happen on pool start and error to client if auth fails
- [x] tenant username and pass stored in Cachex
- [ ] Docs - overview of this behavior
- [ ] Docs - tell people what happens if they change username/pass in tenant db
- [ ] Docs - example auth user query

**Comment by darora** [comment]
I think you'll also require some info (e.g. creds) to verify the client creds?

This is how we configure pgbouncer: https://github.com/supabase/postgres/blob/develop/ansible/files/pgbouncer_config/pgbouncer.ini.j2#L115-L124
