### ISSUE TITLE
[DOCS] Motivation - Efficiency section

### ISSUE THREAD

**Issue by stanislavkozlovski** [supabase/supavisor#153]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)](https://github.com/supabase/supavisor#motivation)

## Describe the problem

> Efficiency: Our customers pay for database processing power, and our goal is to maximize their database capacity. While PgBouncer is resource-efficient, it still consumes some resources on the database instance. By moving connection pooling to a dedicated cluster adjacent to tenant databases, we can free up additional resources to better serve customer queries.

This section is a bit unclear.

One thing I don't understand is - what makes you run PgBouncer in the same EC2 instance as the database? AFAIK, it is well possible to run it in another node outside.

Is there anything blocking you from creating a cluster of PgBouncers adjacent to the databases?

If possible, add more context to the claim.

**Comment by J0** [comment]
Hey @stanislavkozlovski,

Thanks for the query. You are right - it is possible to run in another node outside and it's also possible to create a cluster of PG Bouncers adjacent to the databases. It would require someone to manage the cluster though and I believe Supavisor made more sense for the team given the adoption of Elixir on the Supabase team.

Going to close the issue for now but me know if there are any other unresolved questions or concerns.

Thanks!
