### ISSUE TITLE
Disconnect stale client connections

### ISSUE THREAD

**Issue by chasers** [supabase/supavisor#164]
Stale connections causes clients to hit their connection limits. We need to clean up stale connections with something like a keepalive timeout. 
- [ ] if a client stays connected but doesn't send any packets over the connection for N milliseconds then disconnect client.
- [ ] Start with 60_000 ms and test with Prisma and Vercel / Lambda
- [ ] Put on tenant record 
- [ ] Name it `idle_timeout_downstream` maybe

**Comment by alexboii** [comment]
doesn't this render the feature totally unusable?
