### ISSUE TITLE
ecto failure running in dev (OSx Arm64)

### ISSUE THREAD

**Issue by sabman** [supabase/supavisor#169]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Fails to run in dev on OSX Arm64 Architecture.

Following the instructions on https://github.com/supabase/supavisor/wiki/Installation-and-Usage I am running into the following error when I get to:

`➜ mix ecto.migrate --prefix _supavisor --log-migrator-sql`

```
== Compilation error in file lib/ecto/query.ex ==
** (Kernel.TypespecError) lib/ecto/query.ex:430: type dynamic/0 is a built-in type and it cannot be redefined
    (elixir 1.15.6) lib/kernel/typespec.ex:961: Kernel.Typespec.compile_error/2
    (stdlib 5.0.2) lists.erl:1599: :lists.foldl_1/3
    (elixir 1.15.6) lib/kernel/typespec.ex:226: Kernel.Typespec.translate_typespecs_for_module/2
could not compile dependency :ecto, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ecto --force", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `git checkout v0.9.0`
2. `make db_start`
3. `mix deps.get`
4. `mix ecto.migrate --prefix _supavisor --log-migrator-sql`
The error:
```
== Compilation error in file lib/ecto/query.ex ==
** (Kernel.TypespecError) lib/ecto/query.ex:430: type dynamic/0 is a built-in type and it cannot be redefined
    (elixir 1.15.4) lib/kernel/typespec.ex:961: Kernel.Typespec.compile_error/2
    (stdlib 5.0.2) lists.erl:1599: :lists.foldl_1/3
    (elixir 1.15.4) lib/kernel/typespec.ex:226: Kernel.Typespec.translate_typespecs_for_module/2
could not compile dependency :ecto, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ecto --force", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
```

## System information

- OS: `Darwin Kernel Version 22.6.0: RELEASE_ARM64_T8103 arm64`
- Elixir:
```
➜ mix --version
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Mix 1.15.6 (compiled with Erlang/OTP 26)
```

## Additional context

I have tried upgrading dependencies, upgrading Elixir but none of these helped.

**Comment by abc3** [comment]
Thanks! I'll take a look

**Comment by abc3** [comment]
The [fix](https://github.com/supabase/supavisor/pull/170) has already been merged to main, try it again, please
