### ISSUE TITLE
Cancellation requests are not working

### ISSUE THREAD

**Issue by JelteF** [supabase/supavisor#174]
# Bug report

Cancelling queries is not possible using the Ctrl+C in psql when connecting to postgres to supavisor

## Describe the bug

Clients can send cancellation requests for a connection, and this then cancels the query. This is not implement at all in supavisor.

When pressing Ctrl+C in psql on `select pg_sleep(5)`, I get the following error:
```
23:53:41.111 [error] Client startup message error: :bad_startup_payload file=lib/supavisor/client_handler.ex line=114 pid=<0.917.0>
```

Could be related to #127, since cancellation requests are currently reported as bad startup packets even though they are completely valid parts of the protocol.

**Comment by abc3** [comment]
Thanks for identifying this issue!

**Comment by abc3** [comment]
fixed in https://github.com/supabase/supavisor/pull/194
