### ISSUE TITLE
Can't run the supavisor in docker

### ISSUE THREAD

**Issue by kesavkolla** [supabase/supavisor#218]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Started running supavisor docker container and the container is not starting at all. I am getting the following error:

```
Setting RLIMIT_NOFILE to 100000
eaddrnotavail
Protocol 'inet6_tcp': register/listen error:
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```shell
docker run -d --name pgpool supabase/supavisor:0.9.32
```

## Expected behavior

Container should be up and running.

## System information

- OS: Ubuntu 22.04

**Comment by J0** [comment]
Hey team,

Going to close for now but feel free to let me know if there are still issues with the dockerfile.

Thanks!
