### ISSUE TITLE
Documentation is not clear on how to handle N+1th connection

### ISSUE THREAD

**Issue by jakeleventhal** [supabase/supavisor#227]
# Improve documentation

## Describe the problem

If I have a node with `default_max_clients` set to 1000, what happens with the 1001st connection? Does it get rejected? Or will it be queued to connect? If so is that just governed by the connection timeout in the DB URL?

## Describe the improvement

Make it clear how it handles limitations of the node.

**Comment by chasers** [comment]
Thanks added a FAQ!
