### ISSUE TITLE
Supavisor doesn't handle prisma properly

### ISSUE THREAD

**Issue by jakeleventhal** [supabase/supavisor#233]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [z] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Supabase doesn't pool connections properly for prisma applications running on Next.js via Vercel.

## To Reproduce

I created a minimal reproduction here: https://github.com/jakeleventhal/supabase-test. The README explains how to set up the deployment and links to a relevant 

## Expected behavior

Supavisor should be able to handle thousands of concurrent requests, even on micro, with transaction mode set.

## Screenshots

![image](https://github.com/supabase/supavisor/assets/15133828/597cfa40-0ff6-452d-97a2-3df774fd360d)
![image](https://github.com/supabase/supavisor/assets/15133828/e9832922-84d0-492c-a781-88565ac55f2e)

You can see that after making a bunch of requests, I get errors regarding running out of clients. However, it shows I have plenty of available connections. Supavisor should be able to handle this.

## System information

- OS: macOS
- Browser: Arc
- Version of Node.js: 18.17.1

## Additional context

See the discord thread linked in the repository for a much deeper dive into this.

**Comment by chasers** [comment]
@jakeleventhal thank you for this!! I assume you ran this test recently (the day you posted)?

We think we have a fix in 1.0 which was deployed (also 3 days ago).

**Comment by jakeleventhal** [comment]
I reproduced this a couple days ago as well. So after this was deployed

**Comment by chasers** [comment]
I think we deployed after you tested. Just confirmed it's working for my project.

This project's connection limit is 600, and I fired off 1200 requests without hitting that limit.

<img width="433" alt="Screenshot 2023-12-26 at 11 00 11 AM" src="https://github.com/supabase/supavisor/assets/1019814/c8946590-0f1b-490f-9aea-c335c8fd3b35">

I will experiment some more but this looks to be fixed.

**Comment by chasers** [comment]
<img width="1117" alt="Screenshot 2024-01-03 at 9 32 36 AM" src="https://github.com/supabase/supavisor/assets/1019814/5556abb1-eac9-4f44-a9e6-04f91bd8a9ed">
