### ISSUE TITLE
Supavisor forces request to "postgres" database even when other database is specified

### ISSUE THREAD

**Issue by gitaugakwa** [supabase/supavisor#234]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When attempting to connect to a database that is not named "postgres", supavisor forces the connection to the "postgres" database. This was previously mentioned in the issue https://github.com/supabase/supavisor/issues/187 but has come up again. I had the following discussion on [Discord](https://discord.com/channels/839993398554656828/1187460410782257154).

## To Reproduce

Create a connection to a database other than "postgres" through Supavisor.
Make a query through said connection.
Query would be performed on "postgres" database.

## Expected behavior

Query to be performed on the database stated other than "postgres".

## Screenshots

![Image of Environment Variables used to create connection](https://github.com/supabase/supavisor/assets/50299997/745240e0-67d3-4787-80b3-d18d31b5f2ca)

## System information

- OS: Windows
- Version of supavisor: Version used on supabase.com as of 21/12/2023
- Version of Node.js: v18.17.1

## Additional context

[See the Discord thread linked](https://discord.com/channels/839993398554656828/1187460410782257154)

**Comment by yharaskrik** [comment]
I am also seeing this. We have different databases that we manage via Prisma (that won't be public and we don't want to manage RLS rules on) and would love to be able to use pooling!

**Comment by chasers** [comment]
Got it ... we will fix.

**Comment by abc3** [comment]
Hey, just wanted to inform you that we've recently deployed a fix. We believe the problem should now be resolved. Please feel free to check and confirm whether everything is functioning as expected on your end
