### ISSUE TITLE
server_idle_timeout for DbHandler

### ISSUE THREAD

**Issue by chasers** [supabase/supavisor#274]
See `server_idle_timeout` in PgBouncer. Default is 300 seconds.

Currently with pool_boy database connections are terminated immediately if:
* released from the ClientHandler 
* and there are no waiting connections in the queue

This leads to a lot of new connections to the database up until the point clients are queueing. Not optimal.

The pool should keep a DbHandler around for some configurable amount of time before terminating the connection. 

If unused for some timeout, only then kill the connection.

**Comment by abc3** [comment]
done
