### ISSUE TITLE
Hosted Supavisor closes connection executing query with large result set

### ISSUE THREAD

**Issue by mqp** [supabase/supavisor#294]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When connecting to my Supabase-hosted Supavisor using any client and executing a query that returns a sufficiently large amount of data (order of a gigabyte), Supavisor closes the connection during execution. I identified this with a real query we were running on our backend, but it's easy to reproduce with any old query, e.g. `select generate_series(1, 100000000)`.

It fails reliably every time after about the same time limit. Other long-running queries work OK. It works fine when connecting to the instance directly, and was working fine with pgbouncer.

## To Reproduce

![image](https://github.com/supabase/supavisor/assets/428637/0bf45ab6-6ede-495b-ad95-f3aeb76705a9)

## Additional context

Supabase project ID: pxidrgkatumlvfqaxcll
Postgres version: 15.1

**Comment by abc3** [comment]
Thanks for this finding! We have finished a fix and it will be rolled out on production soon.
