### ISSUE TITLE
Docs should mention  VAULT_ENC_KEY size needs to be 32 chars

### ISSUE THREAD

**Issue by hgezim** [supabase/supavisor#328]
Spent a lot of time trying to find the cause of this.

**Comment by hgezim** [comment]
Related https://github.com/supabase/supavisor/issues/211

**Comment by J0** [comment]
Hey @hgezim,

I'll update the docs to clarify this - quick check in what context did you run into this error? (e.g.  while following `https://supabase.github.io/supavisor/development/setup/`  trying to deploy etc)

**Comment by J0** [comment]
Updated docs to reflect this
