### ISSUE TITLE
Supavisor maintenance in ap-southeast-2 (Sydney) region has caused "Connection terminated unexpectedly" errors

### ISSUE THREAD

**Issue by haydn** [supabase/supavisor#445]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

We're seeing lots of "Connection terminated unexpectedly" errors in our app since [recent maintenance on Supavisor in ap-southeast-2 (Sydney) region](https://status.supabase.com/incidents/jj5199nkl489):

<img width="1491" alt="Screenshot 2024-09-18 at 10 09 58" src="https://github.com/user-attachments/assets/c3f76099-87af-492d-8103-52e43c1b367f">

## To Reproduce

Still trying to reproduce reliably, but it feels very much like this same issue I dealt with a couple of month ago: https://github.com/supabase/supavisor/issues/344

## Expected behavior

You know, not errors.

## Screenshots

See above.

## System information

N/A

## Additional context

I've submitted a support request too. Haven't heard back yet.

**Comment by haydn** [comment]
The only response I've received from Supabase about this so far:

> Thank you for contacting Supabase Support. I am forwarding this to the pooler team to further investigate it.

@abc3 @chasers Is that y'all? I'd love to at least get some insight as to what was changed in that maintenance window.

**Comment by abc3** [comment]
Hey @haydn, sorry that you are experiencing a similar issue again. During maintenance, we deployed a new version but rolled it back after a few hours, so it should be working as before. The reason I haven’t responded to your support ticket yet is that I am still investigating the root cause. However, I will now focus on resolving the problems you're facing with the old version

**Comment by abc3** [comment]
@haydn, is it better now? Feel free to respond here or in the support ticket

**Comment by haydn** [comment]
@abc3 Thanks, it's looking good! Close to 0 errors in the past 2 hours. 👍

<img width="939" alt="image" src="https://github.com/user-attachments/assets/b8bde461-83bf-4d41-9ff9-7c86953327bb">
