### ISSUE TITLE
Implementing SSL Support

### ISSUE THREAD

**Issue by abc3** [supabase/supavisor#47]

**Comment by darora** [comment]
A few things to keep in mind here:

- SSL support for upstream connections
- SSL support for downstream client connections
- Ability to be able to only support SSL'ed connections for downstream clients ("enforce SSL" in our parlance), configurable on a per-tenant basis. Force a disconnect on connected, non-SSL'ed clients if this gets enabled?

Upstream connections currently use a self-signed cert, so you'll likely want to use our CA cert.
