### ISSUE TITLE
Supavisor.Manager will lose its ets state upon process restart

### ISSUE THREAD

**Issue by Dowwie** [supabase/supavisor#68]
The  Supavisor.Manager has an ets table that will erase when the Manager process crashes.  Is this acceptable?

There's a pattern to avoid data loss (I've used it at work):  http://steve.vinoski.net/blog/2011/03/23/dont-lose-your-ets-tables/

I can submit a PR if state persistence is considered useful in this context.

**Comment by chasers** [comment]
Thanks!

Clients are handling manager crashes here: https://github.com/supabase/supavisor/blob/4770b987e06950c5be313f8ca6b08d1fe50d1117/lib/supavisor/client_handler.ex#L182

So they should disconnect if they're `:busy` (to kill it so the end client will reconnect) or resubscribe to the new manager if they're not `:busy`.

We think this is a bit more straight forward, at least for now.
