### ISSUE TITLE
Route lo list all tenants is raising error when there are tenants to list

### ISSUE THREAD

**Issue by dan-de-morais** [supabase/supavisor#83]
# Bug report

- [ x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Route to get tenants `http://localhost:4000/api/tenants` raises an error when there are tenants to list

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Launch the Supavisor application with `make dev`
2. Add a tenant
```
curl -X PUT   'http://localhost:4000/api/tenants/dev_tenant'   --header 'Accept: application/json'   --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQ1MTkyODI0LCJleHAiOjE5NjA3Njg4MjR9.M9jrxyvPLkUxWgOYSf5dNdJ8v_eRrq810ShFRT8N-6M'   --header 'Content-Type: application/json'   --data-raw '{
  "tenant": {
    "db_host": "localhost",
    "db_port": 6432,
    "db_database": "postgres",
    "users": [
      {
        "db_user": "postgres",
        "db_password": "postgres",
        "pool_size": 20,
        "mode_type": "transaction"
      }
    ]
  }
}'
```
3. List all tenants
```
curl -X 'GET'   'http://localhost:4000/api/tenants' --header 'Accept: application/json'   --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQ1MTkyODI0LCJleHAiOjE5NjA3Njg4MjR9.M9jrxyvPLkUxWgOYSf5dNdJ8v_eRrq810ShFRT8N-6M'   --header 'Content-Type: application/json'
```

4. The error will be raised right away
## Expected behavior

No error should be raised and info on all tenants should be displayed 

## Screenshots

![image](https://github.com/supabase/supavisor/assets/101720052/b522fbff-5d48-4d7b-a714-db99f3d793ee)

## System information

- OS: Ubuntu 22.04.1 LTS
- Supavisor's last commit 443c46b62bdd2c0b1ae9b9aded24cd8483dacd15

## Additional context

N/A

## Comment

If this is not a bug, please enlighten me on what i did wrong as i just followed the steps on [Installation-and-Usage](https://github.com/supabase/supavisor/wiki/Installation-and-Usage)

**Comment by abc3** [comment]
Thank you for reporting that ❤️ 
Fixed!
